apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler-scraper-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: image:latest
            command: ["python", "/home/crawler/scraper.py"]
          restartPolicy: OnFailure
