apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-scraper-pgadmin
  namespace: amazon-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin123"
            - name: PGADMIN_LISTEN_PORT
              value: "80"
            - name: PGADMIN_ENABLE_EMAIL
              value: "False"
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: amazon-scraper-pgadmin
  namespace: amazon-scraper
spec:
  type: NodePort # Use LoadBalancer on cloud if preferred
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: pgadmin

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: amazon-scraper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi